name: Append location

on:
  repository_dispatch:
    types: ["l-append"]

concurrency:
  group: append-to-location
  cancel-in-progress: false

jobs:
  append-to-location:
    runs-on: ubuntu-latest
    concurrency:
      group: append-to-location-job
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: location
          fetch-depth: 0
      - name: add
        env:
          L_INPUT_JSON: ${{ toJSON(github.event.client_payload) }}
        run: |
          echo "$L_INPUT_JSON" | jq --compact-output . >> location.jsonl

      - name: Commit changes
        run: |
          git config user.email "auto-location@jamesst.one"
          git config user.name "Automatic update"
          git add .
          git commit -m "Automated location update on $(date)"
          git push -u origin location
